apps/tests/aws-runtime/test/test-service.ts
packages/@eventual/aws-runtime/src/stores/entity-store.ts

`AttributesToGet` is a legacy field and fails when run with not legacy `KeyConditionExpression`.
Added `list` to the tests.

fix: entity list throws dynamo error

---

packages/@eventual/core/src/entity/entity.ts
packages/@eventual/core/src/entity/key.ts
packages/@eventual/core/src/internal/entity.ts
packages/@eventual/core/test/entity.test.ts

Entity did not support optional fields and z.object as attributes input caused compiler error.
See entity.tests.ts

fix: support additional attribute types and fix zod object as attributes

---

apps/test-app-runtime/package.json
apps/test-app/package.json
apps/tests/aws-runtime-cdk/package.json
apps/tests/aws-runtime/package.json
apps/tests/aws-runtime/test/test-service.ts
apps/tests/aws-runtime/test/tester.test.ts
package.json
packages/@eventual/aws-cdk/package.json
packages/@eventual/aws-cdk/src/entity-service.ts
packages/@eventual/aws-runtime/package.json
packages/@eventual/aws-runtime/src/stores/entity-store.ts
packages/@eventual/cli/package.json
packages/@eventual/cli/src/display/event.ts
packages/@eventual/compiler/package.json
packages/@eventual/core-runtime/package.json
packages/@eventual/core-runtime/src/local/stores/entity-store.ts
packages/@eventual/core-runtime/src/stores/entity-store.ts
packages/@eventual/core-runtime/src/workflow-call-executor.ts
packages/@eventual/core/package.json
packages/@eventual/core/src/entity/entity.ts
packages/@eventual/core/src/internal/calls.ts
packages/@eventual/core/src/internal/entity-hook.ts
packages/@eventual/core/src/internal/service-spec.ts
packages/@eventual/integrations-slack/package.json
packages/@eventual/testing/package.json
pnpm-lock.yaml

Add index support for entities. Also upgraded ts-jest (they don't support semantic versioning and the latest version is the first that supports typescript 5).
```ts
const myEntity = entity("myEntity", {
attributes: {
pk: z.string(),
pk2: z.string(),
field1: z.number(),
field2: z.number(),
},
partition: ["pk", "pk2"]
});
// create a GSI with pk as the only key part.
const index1 = myEntity.index("index1", {
partition: ["pk1"]
});
// create a GSI with the original partition key [pk, pk2]
// NOTE: tables without a sort key cannot have LSIs
const index2 = myEntity.index("index2", {
sort: ["field1"]
});
// create a GSI with the partition key [pk], ordered by field1
const index3 = myEntity.index("index3", {
partition: ["pk1"],
sort: ["field1"]
});
const myEntity = entity("myEntity", { …
```

feat: entity index

---

packages/@eventual/aws-runtime/src/stores/entity-store.ts
packages/@eventual/aws-runtime/src/utils.ts
packages/@eventual/core-runtime/src/local/stores/entity-store.ts
packages/@eventual/core-runtime/src/local/stores/pagination.ts
packages/@eventual/core-runtime/src/stores/entity-store.ts
packages/@eventual/core-runtime/src/transaction-executor.ts
packages/@eventual/core-runtime/src/workflow-call-executor.ts
packages/@eventual/core/src/entity/entity.ts
packages/@eventual/core/src/internal/calls.ts
packages/@eventual/core/src/internal/entity-hook.ts

* Adds `scan` to Entity and EntityIndex.
* Adds `consistentRead` to `get` `scan` and `query`.

feat: entity scan

---

apps/tests/aws-runtime/test/test-service.ts
apps/tests/aws-runtime/test/tester.test.ts
packages/@eventual/aws-runtime/src/stores/entity-store.ts
packages/@eventual/core-runtime/src/stores/entity-store.ts

When an Entity has a sort key and that key is a string, omitting the sort key from the query key fails. This is because the sort key is serialized to an empty string instead of undefined as expected and dynamo doesn't allow empty key values.
* Support empty string as a missing sort key when building the query.
* Treat any key key with no provided attributes (or a missing first key attribute) as undefined instead of an empty string.
* Add a test which has a string sort key (previous the sort keys in the tests were all numbers, which didn't have this issue)

fix: entity with sort fails to query without sort

---

apps/tests/aws-runtime/test/test-service.ts
packages/@eventual/compiler/src/eventual-infer.ts
packages/@eventual/compiler/test/__snapshots__/infer-plugin.test.ts.snap
packages/@eventual/core-runtime/src/handlers/command-worker.ts
packages/@eventual/core/src/http/api.ts
packages/@eventual/core/src/http/command.ts
packages/@eventual/core/src/internal/open-api-spec.ts
packages/@eventual/core/src/internal/service-spec.ts

Improving the command output to API Specification.
1. outputs now default to a description of "OK". This description is required by openAPI, unfortunately.
2. allow overriding of the description from the service. Useful for things like openai plugins that may care about the description.
3. allow overriding of the status code for REST path commands. Reflected in the API Spec and the status code returned at runtime. 
4. Would allow a command with a rest path to represent a 304 redirect or be labelled as 204 when no content is returned.
5. allow `api.[method]` commands (pass through) to specify an array of output schemas, descriptions, and status codes. 
6. default schema for RPC and REST commands (not pass through) is now `z.any` instead of undefined.
7. in openapi, this is `{ nullable: …

chore: improve command output

---

apps/tests/aws-runtime/test/test-service.ts
apps/tests/aws-runtime/test/tester.test.ts
packages/@eventual/aws-runtime/src/stores/entity-store.ts
packages/@eventual/core-runtime/src/local/stores/entity-store.ts
packages/@eventual/core-runtime/src/stores/entity-store.ts
packages/@eventual/core-runtime/src/utils.ts
packages/@eventual/core-runtime/test/transaction-executor.test.ts
packages/@eventual/core/src/entity/entity.ts
packages/@eventual/core/src/entity/key.ts
packages/@eventual/core/src/entity/stream.ts
packages/@eventual/core/src/internal/service-spec.ts

* fix - we did not support sparse indices as keys could not be optional
* fix - query key tuple should require the partition
Sparse indices allow optional fields to be used in global or local index keys. 
```ts
export const counter = entity("counter5", {
attributes: {
n: z.number(),
namespace: z.union([
z.literal("different"),
z.literal("default"),
z.literal("another"),
]),
id: z.string(),
optional: z.string().optional(),
},
partition: ["namespace", "id"],
});
export const countersByOptional = counter.index("countersOrderedByNamespace", {
partition: ["id"],
sort: ["optional"],
});
```

 fix: support sparse indicies

---

packages/@eventual/aws-cdk/src/service.ts
packages/@eventual/cli/src/role.ts

Quick workaround to this problem: https://github.com/functionless/eventual/issues/364
I still think we should add a bootstrap stack.

fix: make eventual-cli role region-specific

---

packages/@eventual/core-runtime/src/transaction-executor.ts
packages/@eventual/core-runtime/test/transaction-executor.test.ts

Support some missing transaction behavior which emulates the entity outside of the transaction.
* When an explicit version is given throw an UnexpectedVersion immediately, not at the end. Let the developer handle the error (or let it throw out)
* When a `set` or a `delete` is performed, reflect that if `get` is called again.
* When multiple sets or deletes are performed, the version should only update once, based on the original version (or version + 1 or 0)
* bug: do not retry on unknown error types, but do re-throw them.

feat: support advanced transaction behavior

---

packages/create-eventual/src/create-new-aws-cdk-project.ts

To simplify our project template, i'm adding the cdk cli to the root of the project.

chore: add aws-cdk CLI to root of project

---

.vscode/settings.json
apps/tests/aws-runtime/test/test-service.ts
apps/tests/aws-runtime/test/tester.test.ts
packages/@eventual/aws-runtime/src/stores/entity-store.ts
packages/@eventual/core-runtime/src/local/stores/entity-store.ts
packages/@eventual/core-runtime/src/stores/entity-store.ts
packages/@eventual/core-runtime/test/entity-store.test.ts
packages/@eventual/core/src/entity/key.ts
packages/@eventual/core/src/internal/entity-hook.ts
packages/@eventual/core/src/internal/entity.ts

Adds the ability to provide query conditions in place of concrete key attributes for the sort key.
* Between
* Begins with - only string values
* Less/Greater Than [Equal]
```ts
myEntity.query({
part: "hello",
sort: { $between: [1, 100] }
});
myEntity.query({
part: "hello",
sort1: "a",
sort2: { $gt: "b" }
});
myEntity.query({
part: "hello",
$between: [{ sort1: "a", sort2: "1" }, { sort1: "b", sort2: "2" }]
});
```
Caveats:
* Numeric fields will be evaluated as strings when part of a multi-attribute key part.
* ex: `["name", "age"]`, `{ name: "sam", age: { $gt: 30 } }` - greatThan 30 will use string based "30" and not numeric
----
* ~~TODO: add documentation~~

feat: entity query conditions

---

packages/@eventual/aws-cdk/src/bucket-service.ts
packages/@eventual/compiler/src/eventual-infer.ts
packages/@eventual/core/src/bucket.ts
packages/@eventual/core/src/internal/service-spec.ts

I needed to be able to enable versioning on a bucket and noticed that we did not have the full escape hatch enabled for buckets.

feat: allow for all BucketProps as overrides

---

packages/@eventual/client/src/http-eventual-client.ts

Removes the async_hooks module from the import path of the client
It is a trade off. Hard code `"_system"` value in the client to remove the dependency.
This is acceptable because the client needs to be usable everywhere and this value cannot change without breaking infrastructure.

fix: do not import @eventual/core/internal in @eventual/client

---

packages/create-eventual/src/create-new-aws-cdk-project.ts
packages/create-eventual/src/sample-code.ts

Worked locally
```ts
$ ts-node ./eventual/packages/create-eventual/bin/index.js 
$ pnpm eventual local --offline --port 3112
✔ Eventual Dev Server running on http://localhost:3112
$ cat infra/src/app.mts 
import { App, Stack, CfnOutput } from "aws-cdk-lib";
import { Service } from "@eventual/aws-cdk";
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const app = new App();
const stack = new Stack(app, "eventual-esm")
import type * as eventualesm from "@eventual-esm/service"
const service = new Service<typeof eventualesm>(stack, "Service", {
name: "eventual-esm",
entry: require.resolve("@eventual-esm/service")
});
```

feat: create cdk with esm

---

apps/tests/aws-runtime/test/test-service.ts
packages/@eventual/aws-runtime/src/stores/entity-store.ts
packages/@eventual/cli/src/display/event.ts
packages/@eventual/core-runtime/src/local/stores/entity-store.ts
packages/@eventual/core-runtime/src/stores/entity-store.ts
packages/@eventual/core-runtime/src/transaction-executor.ts
packages/@eventual/core-runtime/test/command-executor.test.ts
packages/@eventual/core-runtime/test/transaction-executor.test.ts
packages/@eventual/core/src/entity/entity.ts
packages/@eventual/core/test/infer.test.ts
packages/@eventual/testing/test/env.test.ts

Closes #404
BREAKING CHANGE: `entity.set` is now `entity.put`. All reference to set, for example in transaction operations and types, are also now "put".

chore: rename entity.set to entity.put

---

packages/@eventual/aws-runtime/src/create.ts
packages/@eventual/aws-runtime/src/handlers/bucket-handler-worker.ts
packages/@eventual/aws-runtime/src/handlers/command-worker.ts
packages/@eventual/aws-runtime/src/handlers/entity-stream-worker.ts
packages/@eventual/aws-runtime/src/handlers/orchestrator.ts
packages/@eventual/aws-runtime/src/handlers/subscription-worker.ts
packages/@eventual/aws-runtime/src/handlers/task-worker.ts
packages/@eventual/core-runtime/src/workflow/call-executor.ts

Found by @mattduran420
When a service did not have an open search index, commands, workflows and more would fail. Use the service spec to determine if the client needs to be created or now (presence of an index) which matches the logic to create the infra in CDK.
Ran the runtime tests without open search and proved that all workflows and commands did stop working.
After this change, tests pass without and without open search.
```
{
"errorType": "Error",
"errorMessage": "Expected env variable EVENTUAL_OPENSEARCH_ENDPOINT to be present.",
"stack": [
"Error: Expected env variable EVENTUAL_OPENSEARCH_ENDPOINT to be present.",
"    at assertNonNull (/packages/@eventual/core/src/internal/util.ts:9:11)",
"    at tryGetEnv (/packages/@eventual/aws-runtime/src/env.ts:32:10)",
"    at …
```

fix: service without open search throws errors

---

packages/@eventual/aws-cdk/src/command-service.ts
packages/@eventual/aws-cdk/src/constructs/spec-http-api.ts
packages/@eventual/aws-cdk/src/service.ts

Requested by @mattduran420. Support a few overrides for api gateway, for example, adding a custom domain in CDK.

feat: support api cdk overrides

---

apps/tests/aws-runtime/test/test-service.ts
apps/tests/aws-runtime/test/tester.test.ts
packages/@eventual/aws-runtime/src/handlers/entity-stream-worker.ts
packages/@eventual/aws-runtime/src/stores/entity-store.ts

When calling `Entity.put` in a workflow with undefined values or calling `Entity.put` anywhere with missing attributes, if that attribute previously was set, it would not be removed.
This is because we use update to compute the version for `Entity.put`.
Updated `Entity.put` to remove any attributes not in the object instead.

fix: entity remove missing attributes

---

apps/tests/aws-runtime/test/test-service.ts
packages/@eventual/aws-runtime/src/stores/entity-store.ts
packages/@eventual/cli/src/commands/local.ts
packages/@eventual/core-runtime/src/local/stores/entity-store.ts
packages/@eventual/core-runtime/src/workflow/call-executors-and-factories/transaction-call.ts

* BUG: Transaction in a workflow would error instead of returning a successful response
* Bad change during the executor refactor that assumed the base transaction executor return an object with success/fail and not just an object.
* BUG: In a transaction the condition operation would fail if the version was 0 (aka, should not exist yet). 
* This happens when a entity.get return undefined within a transaction and we want to assert that the item doesn't exist by the end of the transaction.
* Root Cause: a EntityAttributeValueMap key was being created for expected version when the value was defined, but only used when defined or not 0.
* Solution: Fixed the logic to match.
* BUG: In Local, transaction could conflict when started at overlapping intervals. 
* This was because the local …

fix: transaction in a workflow transform error

---

packages/@eventual/aws-cdk/src/build.ts
packages/@eventual/core/src/function-props.ts
packages/@eventual/core/src/internal/service-spec.ts
packages/@eventual/core/src/subscription.ts
packages/@eventual/core/src/task.ts

Support the ability to mark a module as external when bundling a handler.
```ts
command("myCommand", {externalModules: ["typescript"]}, async () => {});
```

feat: external function modules

---

.github/workflows/build.yml
apps/tests/aws-runtime-cdk/src/chaos-extension.ts
apps/tests/aws-runtime/package.json
apps/tests/aws-runtime/scripts/test-cli
apps/tests/aws-runtime/test/env.ts
packages/@eventual/aws-cdk/src/command-service.ts
packages/@eventual/cli/src/commands/logs.ts

The logs lambda was timing out and then silently failing the logs command. Added error reporting to the logs command along with an increased timeout on the system command lambda.
Also refactored the build/test github action to be smaller units in with more in parallel.

fix: cli tests randomly fail

---

packages/@eventual/core-runtime/src/local/stores/entity-store.ts
packages/@eventual/core-runtime/test/local-bucket-store.test.ts
packages/@eventual/core-runtime/test/local-entity-store.test.ts

If the .eventual/local folder was missing an index (new/deleted), `index.query` would fail on query. change the logic to create requested indices on demand if they were not originally loaded.
TODO: Compute missing local indices on load for existing data https://github.com/functionless/eventual/issues/464

fix: local entity index query failed when index was missing from local data

---

packages/@eventual/core-runtime/src/local/stores/bucket-store.ts

We should not modify the string data written to S3 when persisting local.

fix: do not encode string as JSON when writing to S3 local
